// Lista completa de ciudades de Latinoamérica para autocompletado
export const cities = [
  // ========== ARGENTINA ==========
  'Buenos Aires, Argentina',
  'Córdoba, Argentina',
  'Rosario, Argentina',
  'Mendoza, Argentina',
  'San Miguel de Tucumán, Argentina',
  'La Plata, Argentina',
  'Mar del Plata, Argentina',
  'Salta, Argentina',
  'Santa Fe, Argentina',
  'San Juan, Argentina',
  'Resistencia, Argentina',
  'Neuquén, Argentina',
  'Santiago del Estero, Argentina',
  'Corrientes, Argentina',
  'Bahía Blanca, Argentina',
  'Posadas, Argentina',
  'San Salvador de Jujuy, Argentina',
  'Paraná, Argentina',
  'Formosa, Argentina',
  'San Luis, Argentina',
  'Catamarca, Argentina',
  'Río Cuarto, Argentina',
  'Comodoro Rivadavia, Argentina',
  'Concordia, Argentina',
  'San Rafael, Argentina',
  'San Nicolás de los Arroyos, Argentina',
  'Tandil, Argentina',
  'Villa María, Argentina',
  'San Carlos de Bariloche, Argentina',
  'Río Gallegos, Argentina',
  'Ushuaia, Argentina',
  'Rawson, Argentina',
  'La Rioja, Argentina',
  'Viedma, Argentina',
  'Olavarría, Argentina',
  'Junín, Argentina',
  'Pergamino, Argentina',
  'Rafaela, Argentina',
  'Venado Tuerto, Argentina',
  'Trelew, Argentina',

  // ========== MÉXICO ==========
  'Ciudad de México, México',
  'Guadalajara, México',
  'Monterrey, México',
  'Puebla, México',
  'Toluca, México',
  'Tijuana, México',
  'León, México',
  'Ciudad Juárez, México',
  'Querétaro, México',
  'San Luis Potosí, México',
  'Mérida, México',
  'Aguascalientes, México',
  'Chihuahua, México',
  'Morelia, México',
  'Cancún, México',
  'Saltillo, México',
  'Hermosillo, México',
  'Mexicali, México',
  'Culiacán, México',
  'Acapulco, México',
  'Veracruz, México',
  'Tuxtla Gutiérrez, México',
  'Villahermosa, México',
  'Reynosa, México',
  'Oaxaca, México',
  'Durango, México',
  'Tampico, México',
  'Cuernavaca, México',
  'Mazatlán, México',
  'Xalapa, México',
  'Celaya, México',
  'Irapuato, México',
  'Tepic, México',
  'Ensenada, México',
  'Campeche, México',
  'Colima, México',
  'Pachuca, México',
  'Tlaxcala, México',
  'Zacatecas, México',
  'Playa del Carmen, México',
  'Los Cabos, México',
  'Puerto Vallarta, México',
  'Guanajuato, México',
  'San Cristóbal de las Casas, México',
  'Taxco, México',
  'La Paz, México',
  'Chetumal, México',

  // ========== COLOMBIA ==========
  'Bogotá, Colombia',
  'Medellín, Colombia',
  'Cali, Colombia',
  'Barranquilla, Colombia',
  'Cartagena, Colombia',
  'Cúcuta, Colombia',
  'Bucaramanga, Colombia',
  'Pereira, Colombia',
  'Santa Marta, Colombia',
  'Ibagué, Colombia',
  'Manizales, Colombia',
  'Pasto, Colombia',
  'Neiva, Colombia',
  'Villavicencio, Colombia',
  'Armenia, Colombia',
  'Valledupar, Colombia',
  'Montería, Colombia',
  'Sincelejo, Colombia',
  'Popayán, Colombia',
  'Tunja, Colombia',
  'Florencia, Colombia',
  'Riohacha, Colombia',
  'Quibdó, Colombia',
  'Yopal, Colombia',
  'Leticia, Colombia',

  // ========== CHILE ==========
  'Santiago, Chile',
  'Valparaíso, Chile',
  'Concepción, Chile',
  'Antofagasta, Chile',
  'Viña del Mar, Chile',
  'Temuco, Chile',
  'Rancagua, Chile',
  'Talca, Chile',
  'Arica, Chile',
  'Iquique, Chile',
  'Puerto Montt, Chile',
  'Chillán, Chile',
  'Osorno, Chile',
  'Valdivia, Chile',
  'Calama, Chile',
  'Copiapó, Chile',
  'La Serena, Chile',
  'Coquimbo, Chile',
  'Punta Arenas, Chile',
  'Los Ángeles, Chile',
  'Curicó, Chile',
  'Linares, Chile',

  // ========== PERÚ ==========
  'Lima, Perú',
  'Arequipa, Perú',
  'Trujillo, Perú',
  'Chiclayo, Perú',
  'Piura, Perú',
  'Iquitos, Perú',
  'Cusco, Perú',
  'Huancayo, Perú',
  'Tacna, Perú',
  'Chimbote, Perú',
  'Juliaca, Perú',
  'Puno, Perú',
  'Cajamarca, Perú',
  'Sullana, Perú',
  'Ayacucho, Perú',
  'Huánuco, Perú',
  'Tarapoto, Perú',
  'Pucallpa, Perú',
  'Tumbes, Perú',
  'Ica, Perú',

  // ========== ECUADOR ==========
  'Quito, Ecuador',
  'Guayaquil, Ecuador',
  'Cuenca, Ecuador',
  'Santo Domingo, Ecuador',
  'Machala, Ecuador',
  'Durán, Ecuador',
  'Manta, Ecuador',
  'Portoviejo, Ecuador',
  'Loja, Ecuador',
  'Ambato, Ecuador',
  'Riobamba, Ecuador',
  'Esmeraldas, Ecuador',
  'Ibarra, Ecuador',
  'Latacunga, Ecuador',
  'Babahoyo, Ecuador',

  // ========== VENEZUELA ==========
  'Caracas, Venezuela',
  'Maracaibo, Venezuela',
  'Valencia, Venezuela',
  'Barquisimeto, Venezuela',
  'Maracay, Venezuela',
  'Ciudad Guayana, Venezuela',
  'Barcelona, Venezuela',
  'Maturín, Venezuela',
  'San Cristóbal, Venezuela',
  'Cumaná, Venezuela',
  'Mérida, Venezuela',
  'Barinas, Venezuela',
  'Puerto La Cruz, Venezuela',
  'Los Teques, Venezuela',
  'Coro, Venezuela',

  // ========== URUGUAY ==========
  'Montevideo, Uruguay',
  'Salto, Uruguay',
  'Paysandú, Uruguay',
  'Las Piedras, Uruguay',
  'Rivera, Uruguay',
  'Maldonado, Uruguay',
  'Tacuarembó, Uruguay',
  'Melo, Uruguay',
  'Mercedes, Uruguay',
  'Artigas, Uruguay',
  'Durazno, Uruguay',
  'Florida, Uruguay',
  'Colonia del Sacramento, Uruguay',
  'Punta del Este, Uruguay',
  'Treinta y Tres, Uruguay',

  // ========== PARAGUAY ==========
  'Asunción, Paraguay',
  'Ciudad del Este, Paraguay',
  'San Lorenzo, Paraguay',
  'Luque, Paraguay',
  'Capiatá, Paraguay',
  'Lambaré, Paraguay',
  'Fernando de la Mora, Paraguay',
  'Encarnación, Paraguay',
  'Pedro Juan Caballero, Paraguay',
  'Caaguazú, Paraguay',
  'Coronel Oviedo, Paraguay',
  'Concepción, Paraguay',

  // ========== BOLIVIA ==========
  'La Paz, Bolivia',
  'Santa Cruz de la Sierra, Bolivia',
  'Cochabamba, Bolivia',
  'Sucre, Bolivia',
  'Oruro, Bolivia',
  'Tarija, Bolivia',
  'Potosí, Bolivia',
  'Trinidad, Bolivia',
  'Cobija, Bolivia',
  'Riberalta, Bolivia',

  // ========== BRASIL ==========
  'São Paulo, Brasil',
  'Río de Janeiro, Brasil',
  'Brasilia, Brasil',
  'Salvador, Brasil',
  'Fortaleza, Brasil',
  'Belo Horizonte, Brasil',
  'Manaus, Brasil',
  'Curitiba, Brasil',
  'Recife, Brasil',
  'Porto Alegre, Brasil',
  'Belém, Brasil',
  'Goiânia, Brasil',
  'Guarulhos, Brasil',
  'Campinas, Brasil',
  'São Luís, Brasil',
  'Maceió, Brasil',
  'Natal, Brasil',
  'Campo Grande, Brasil',
  'Florianópolis, Brasil',
  'João Pessoa, Brasil',
  'Teresina, Brasil',
  'Cuiabá, Brasil',
  'Aracaju, Brasil',
  'Vitória, Brasil',
  'Porto Velho, Brasil',

  // ========== CENTROAMÉRICA ==========
  // Costa Rica
  'San José, Costa Rica',
  'Alajuela, Costa Rica',
  'Heredia, Costa Rica',
  'Cartago, Costa Rica',
  'Liberia, Costa Rica',
  'Puntarenas, Costa Rica',
  'Limón, Costa Rica',

  // Panamá
  'Ciudad de Panamá, Panamá',
  'San Miguelito, Panamá',
  'David, Panamá',
  'Colón, Panamá',
  'Santiago, Panamá',
  'Chitré, Panamá',

  // Guatemala
  'Ciudad de Guatemala, Guatemala',
  'Mixco, Guatemala',
  'Villa Nueva, Guatemala',
  'Quetzaltenango, Guatemala',
  'Escuintla, Guatemala',
  'Cobán, Guatemala',
  'Huehuetenango, Guatemala',
  'Antigua Guatemala, Guatemala',

  // Honduras
  'Tegucigalpa, Honduras',
  'San Pedro Sula, Honduras',
  'La Ceiba, Honduras',
  'Choloma, Honduras',
  'El Progreso, Honduras',
  'Comayagua, Honduras',

  // El Salvador
  'San Salvador, El Salvador',
  'Santa Ana, El Salvador',
  'San Miguel, El Salvador',
  'Soyapango, El Salvador',
  'Santa Tecla, El Salvador',
  'Apopa, El Salvador',

  // Nicaragua
  'Managua, Nicaragua',
  'León, Nicaragua',
  'Masaya, Nicaragua',
  'Chinandega, Nicaragua',
  'Matagalpa, Nicaragua',
  'Granada, Nicaragua',
  'Estelí, Nicaragua',

  // ========== CARIBE ==========
  // Cuba
  'La Habana, Cuba',
  'Santiago de Cuba, Cuba',
  'Camagüey, Cuba',
  'Holguín, Cuba',
  'Santa Clara, Cuba',
  'Guantánamo, Cuba',
  'Bayamo, Cuba',

  // República Dominicana
  'Santo Domingo, República Dominicana',
  'Santiago de los Caballeros, República Dominicana',
  'San Pedro de Macorís, República Dominicana',
  'La Romana, República Dominicana',
  'San Cristóbal, República Dominicana',
  'Puerto Plata, República Dominicana',
  'Punta Cana, República Dominicana',

  // Puerto Rico
  'San Juan, Puerto Rico',
  'Bayamón, Puerto Rico',
  'Carolina, Puerto Rico',
  'Ponce, Puerto Rico',
  'Mayagüez, Puerto Rico'
];
